flights/urls.py
from django.urls import path
from .views import book_flight, flight_status, signup, review_flight, select_flight

app_name = 'flights'
urlpatterns = [
    path('', book_flight, name='search_flights'),
    path('status/', flight_status, name='flight_status'),
    path('select/', select_flight, name='select_flight'),
    path('review/', review_flight, name='review_flight'),
    path('signup/', signup, name='signup')
]

fly_airtech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from flights import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('flights/', include('flights.urls', namespace='flights')),
    path('bookings/', include('bookings.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flights/models.py
from django.db.models import Model, CharField, DateTimeField, DecimalField, PositiveSmallIntegerField, DurationField, \
    ForeignKey, SET_NULL
from .utils import get_flight_duration, add_time


class Location(Model):
    """A class to define the various travel locations"""

    iata = CharField(max_length=3)
    airport = CharField(max_length=100)
    city = CharField(max_length=50)
    country = CharField(max_length=50)
    latitude = DecimalField(max_digits=9, decimal_places=6)
    longitude = DecimalField(max_digits=9, decimal_places=6)

    def __str__(self):
        return f"{self.city}, {self.country}"


class Aircraft(Model):
    """A class defining available Air crafts"""

    manufacturer = CharField(max_length=50)
    model = CharField(max_length=50)
    capacity = PositiveSmallIntegerField(default=500)

    def __str__(self):
        return f"{self.manufacturer} {self.model}"


class FlightStatus(Model):
    """A class defining the status of a Flight"""

    name = CharField(max_length=50)

    def __str__(self):
        return self.name


class Flight(Model):
    """A typical class defining a flight"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__last_scheduled = self.scheduled
        self.__last_datetime_update = self.last_update

    flight_number = CharField(max_length=20, unique=True, help_text='Enter flight number')
    departure = ForeignKey(Location, on_delete=SET_NULL, null=True)
    destination = ForeignKey(Location, on_delete=SET_NULL, null=True, related_name='destination_set')
    flight_duration = DurationField(blank=True)
    scheduled = DateTimeField()
    last_update = DateTimeField(blank=True)
    arrival = DateTimeField(blank=True)
    flight_status = ForeignKey(FlightStatus, on_delete=SET_NULL, null=True, default=1)
    aircraft = ForeignKey(Aircraft, on_delete=SET_NULL, null=True)
    price_economy = DecimalField(max_digits=9, decimal_places=2)
    price_business = DecimalField(max_digits=9, decimal_places=2)
    created_at = DateTimeField(auto_now_add=True)
    updated_at = DateTimeField(auto_now=True)

    __last_scheduled = None
    __last_datetime_update = None

    def save(self, *args, **kwargs):
        if not self.flight_duration:
            duration = get_flight_duration(self.departure, self.destination)
            self.flight_duration = duration
        if not self.last_update or self.scheduled != self.__last_scheduled:
            self.last_update = self.scheduled
        if self.last_update != self.__last_datetime_update:
            self.arrival = add_time(self.last_update, self.flight_duration)
        super().save(*args, **kwargs)
        self.__last_datetime_update = self.last_update
        self.__last_scheduled = self.scheduled

    def __str__(self):
        return f"{self.flight_number}, {self.departure.city} - {self.destination.city}"

flights/forms.py
from django.forms import Form, ModelChoiceField, DateField, IntegerField, CharField, EmailField, DateInput, Select
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Location
from .utils import tomorrow


class MyDateInput(DateInput):
    input_type = 'date'


class MyDateField(DateField):
    widget = MyDateInput


class SearchFlights(Form):
    from_location = ModelChoiceField(queryset=Location.objects.all(),
                                     empty_label='Select Airport',
                                     label='From',
                                     widget=Select(attrs={'placeholder': 'From'}))
    to_location = ModelChoiceField(queryset=Location.objects.all(),
                                   empty_label='Select Airport',
                                   label='To',
                                   widget=Select(attrs={'placeholder': 'To'}))
    departure_date = MyDateField(label='Departing',
                                 widget=MyDateInput(attrs={'min': tomorrow}))
    returning_date = MyDateField(label='Returning',
                                 required=False,
                                 widget=MyDateInput(attrs={'min': tomorrow}))
    adults = IntegerField(min_value=0, max_value=5)
    children = IntegerField(min_value=0, max_value=5, required=False)
    infants = IntegerField(min_value=0, max_value=5, required=False)


class FlightStatusByAirport(Form):
    from_location = ModelChoiceField(queryset=Location.objects.all(),
                                     empty_label='Select Airport',
                                     label='From')
    to_location = ModelChoiceField(queryset=Location.objects.all(),
                                   empty_label='Select Airport',
                                   label='To')
    departure_date = MyDateField(label='Flight Date')


class FlightStatusByNumber(Form):
    flight_number = CharField(max_length=20)


class SignUpForm(UserCreationForm):
    first_name = CharField(max_length=30, required=False)
    last_name = CharField(max_length=30, required=False)
    email = EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

flights/views.py
import json
from django.contrib.auth import login, authenticate
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import SearchFlights, FlightStatusByAirport, FlightStatusByNumber, SignUpForm
from .models import Flight
from .utils import flight_date_range, generate_flight_dates


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=raw_password)
            if user is not None:
                login(request, user)
            return redirect('profile')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def index(request):
    search_flights = SearchFlights()
    flight_status_by_airport = FlightStatusByAirport()
    flight_status_by_number = FlightStatusByNumber()
    return render(request, 'index.html',
                  {'title': 'Home',
                   'search_flights': search_flights,
                   'flight_status_by_airport': flight_status_by_airport,
                   'flight_status_by_number': flight_status_by_number})


def book_flight(request):
    if request.method == 'POST':
        form = SearchFlights(request.POST)
        if form.is_valid():
            search = form.cleaned_data
            request.session['passengers'] = {
                'adult': search['adults'],
                'child': search['children'],
                'infant': search['infants']
            }
            departure_date_range = flight_date_range(search['departure_date'])
            departure_results = list(Flight.objects.filter(
                departure=search['from_location'],
                destination=search['to_location'],
                last_update__date__range=departure_date_range))
            departure_flights = generate_flight_dates(departure_date_range, departure_results)
            return_flights = None
            if search['returning_date']:
                return_date_range = flight_date_range(search['returning_date'])
                return_results = list(Flight.objects.filter(
                    departure=search['to_location'],
                    destination=search['from_location'],
                    last_update__date__range=return_date_range))
                return_flights = generate_flight_dates(return_date_range, return_results)

            return render(request, 'flights.html',
                          {'title': 'Flights Now',
                           'departure_flights': departure_flights,
                           'return_flights': return_flights,
                           'search': search,
                           'form': form})
    return render(request, 'flights.html', {'title': 'Flights'})


def flight_status(request):
    if request.method == 'POST':
        status_by_airport = FlightStatusByAirport(request.POST) if 'from_location' in request.POST else None
        status_by_number = FlightStatusByNumber(request.POST) if 'flight_number' in request.POST else None
        flight = None
        if status_by_number and status_by_number.is_valid():
            query = status_by_number.cleaned_data
            flight = Flight.objects.filter(flight_number=query['flight_number'])
        elif status_by_airport and status_by_airport.is_valid():
            query = status_by_airport.cleaned_data
            flight = Flight.objects.filter(
                departure=query['from_location'],
                destination=query['to_location'],
                last_update__date=query['departure_date'])

        if status_by_number:
            status_by_airport = FlightStatusByAirport()
        else:
            status_by_number = FlightStatusByNumber()

        return render(request, 'flight_status.html',
                      {'title': 'Check flight status',
                       'flights': flight,
                       'flight_status_by_number': status_by_number,
                       'flight_status_by_airport': status_by_airport})
    return render(request, 'flight_status.html', {'title': 'Check flight status'})


def select_flight(request):
    if request.method == 'POST':
        flight_str = request.body.decode(encoding='UTF-8')
        json_obj = json.loads(flight_str)
        request.session['flights'] = json_obj
        response = json.dumps({'data': 'success'})
        return HttpResponse(content=response, content_type='application/json', status=200)


def review_flight(request):
    selected_flights = request.session['flights']
    passengers = request.session['passengers']
    total_passengers = passengers['adult'] + (passengers['child'] or 0) + (passengers['infant'] or 0)
    outbound_flight_id = int(selected_flights['outbound']['flightId'])
    outbound_flight = Flight.objects.get(id=outbound_flight_id)
    outbound_class = selected_flights['outbound']['flightClass']
    outbound_flight_price = outbound_flight.price_economy * total_passengers if outbound_class == 'economy' \
        else outbound_flight.price_business * total_passengers
    inbound_flight = None
    inbound_class = None
    inbound_flight_price = 0

    if selected_flights['inbound']:
        inbound_flight_id = int(selected_flights['inbound']['flightId'])
        inbound_flight = Flight.objects.get(id=inbound_flight_id)
        inbound_class = selected_flights['inbound']['flightClass']
        inbound_flight_price = inbound_flight.price_economy * total_passengers if inbound_class == 'economy' \
            else inbound_flight.price_business * total_passengers

    total_price = outbound_flight_price + inbound_flight_price
    request.session['price'] = float(total_price)
    return render(request, 'review_flight.html',
                  {'title': 'Review Flight',
                   'passengers': passengers,
                   'total_price': total_price,
                   'outbound_flight': outbound_flight,
                   'outbound_class': outbound_class,
                   'inbound_flight': inbound_flight,
                   'inbound_class': inbound_class})

flights/templates/flight_status.html
{% extends "base.html" %}
{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block content %}
    <main class="container">
    <h6 class="m-3">Use one of the following options to search for your flight</h6>
        <section class="flight-forms">
            <ul class="nav nav-tabs nav-fill" id="form-switcher" role="tablist">
                <li class="nav-item">
                    <a class="nav-link" id="status-by-airport-tab" data-toggle="tab" role="tab"
                       aria-controls="status-by-airport" aria-selected="true" href="#status-by-airport">
                        Airport
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#status-by-number" id="status-by-number-tab" data-toggle="tab" role="tab"
                        aria-controls="status-by-number" aria-selected="true">
                        Flight Number
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div id="status-by-airport" class="tab-pane fade" role="tabpanel"
                     aria-labelledby="status-by-airport-tab">
                    <form action="{% url 'flights:flight_status' %}" method="POST" class="status-form" id="by-airport">
                        {% csrf_token %}
                        {{ flight_status_by_airport }}
                        <input type="submit" class="btn btn-primary text-light submit-status-airport"
                               value="Display Flight Status">
                    </form>
                </div>
                <div id="status-by-number" class="tab-pane fade show active" role="tabpanel" aria-labelledby="status-by-number-tab">
                    <form action="{% url 'flights:flight_status' %}" method="POST" class="status-form"
                          id="status-by-number">
                        {% csrf_token %}
                        {{ flight_status_by_number }}
                        <input type="submit" class="btn btn-primary text-light submit-status-number"
                               value="Display Flight Status">
                    </form>
                </div>
            </div>
        </section>
        <section>
        {% if flights %}
            <header class="book-flights-header">Flight Status Result</header>
            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Flight Number</th>
                            <th scope="col">From</th>
                            <th scope="col">To</th>
                            <th scope="col">Scheduled</th>
                            <th scope="col">Last Update</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for flight in flights %}
                        <tr>
                            <td>{{ flight.flight_number }}</td>
                            <td>{{ flight.departure }}</td>
                            <td>{{ flight.destination }}</td>
                            <td>{{ flight.scheduled }}</td>
                            <td>{{ flight.last_update }}</td>
                            <td>{{ flight.flight_status }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <p><i class="fas fa-info-circle"></i> All times are in West African Time (GMT +1)</p>
            </div>
        {% else %}
            <div class="m-4 p-4 text-center">
                <p>We could not find your flight from the information given. Please try again!</p>
            </div>
        {% endif %}
        </section>
    </main>
{% endblock %}

flights/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    <title>Home</title>
{% endblock %}

{% block content %}
    <main>
        <header id="fw-image">
            <img src="{% static "flights/images/air.jpg" %}"
                 srcset="{% static "flights/images/air0.jpg" %} 500w,
                        {% static "flights/images/air.jpg" %} 1200w,
                        {% static "flights/images/air2.jpg" %} 2000w"
                 alt="Air"
            />
            <p class="text-light">Fly...<br> in comfort</p>
        </header>
        <section class="container flight-forms">
            <ul class="nav nav-tabs nav-fill" id="form-switcher" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="book-tab" data-toggle="tab" role="tab" aria-controls="book"
                       aria-selected="true" href="#book">
                        Book Flight
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#flights" id="flights-tab" data-toggle="tab" role="tab"
                        aria-controls="flights" aria-selected="true">
                        Flight Status
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div id="book" class="tab-pane fade show active" role="tabpanel" aria-labelledby="book-tab">
                    <div class="trip-mode-switch">
                        <div class="form-check">
                            <label class="trip-mode" for="round-trip">Round Trip</label>
                            <input class="trip-mode-label" type="radio" name="round_trip" id="round-trip" checked>
                        </div>
                        <div class="form-check">
                            <label class="trip-mode" for="one-way">One way</label>
                            <input class="trip-mode-label" type="radio" name="one_way" id="one-way">
                        </div>
                    </div>
                     <form action="{% url 'flights:search_flights' %}" method="POST" class="book-form">
                        {% csrf_token %}
                        {{ search_flights }}
                         <input type="submit" class="btn pry-color text-light submit-flight-search" value="Search Flights">
                    </form>
                </div>
                <div id="flights" class="tab-pane fade" role="tabpanel" aria-labelledby="flights-tab">
                    <form action="{% url 'flights:flight_status' %}" method="POST" class="status-form" id="by-airport">
                        {% csrf_token %}
                        {{ flight_status_by_airport }}
                        <input type="submit" class="btn pry-color text-light submit-status-airport" value="Display Flight Status">
                    </form>
                    <span>OR</span>
                    <form action="{% url 'flights:flight_status' %}" method="POST" class="status-form" id="by-number">
                        {% csrf_token %}
                        {{ flight_status_by_number }}
                        <input type="submit" class="btn pry-color text-light submit-status-number" value="Display Flight Status">
                    </form>
                </div>
            </div>
        </section>
        <section class="container how-to-section">
            <div class="row">
                <article class="how-to col-sm">
                    <div>
                        <i class="fas fa-search fa-2x"></i>
                    </div>
                    <p>Search for flights to a destination of your choice within Nigeria.</p>
                </article>
                <article class="how-to col-sm">
                    <div>
                        <i class="fas fa-cart-plus fa-2x"></i>
                    </div>
                    <p>Flights are scheduled for your comfort and convenience so no stress for you.</p>
                </article>
                <article class="how-to col-sm">
                    <div>
                        <i class="far fa-credit-card fa-2x"></i>
                    </div>
                    <p>Book your flights and pay online with an option to book on-hold and pay later.</p>
                </article>
            </div>
        </section>
    </main>
{% endblock %}

flights/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <main class="container d-flex flex-column align-items-center justify-content-center">
        <h2>Sign up</h2>
            <form action="{% url 'flights:signup' %}" method="post" class="signup-form">
                {% csrf_token %}
                {{ form }}
                <input type="submit" class="btn btn-primary btn-block" value="Sign Up" />
            </form>
        <p><a href="{% url 'login' %}">Already have an account?</a></p>
    </main>
{% endblock %}